apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: banking-report-batch
  description: "Processamento em lote de relatórios bancários para contas correntes"
  annotations:
    github.com/project-slug: emanueldeveloper82/banking-report-batch
    backstage.io/techdocs-ref: dir:.
spec:
  type: badground-job
  lifecycle: production
  owner: group:conta-corrente
  domain: financeiro
  system: system:banking-system
  providesApis:
    - banking-report-batch-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: banking-report-batch-api
  description: "Especificação OpenAPI do Banking Report Batch"
spec:
  type: openapi
  lifecycle: production
  owner: group:conta-corrente
  system: system:banking-system
  definition:
    $text: ./openapi.yaml
